# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Test Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: 'npm'
    - name: Install Dependencies 
      run: npm install  
    - name: Start Server
      run: npm run server &
    - name: Start Frontend
      run: npm run start &
    - name: Start Tests
      run: npm run test    
